import {
  mdiViewDashboardOutline,
  mdiAccountMultiple,
  mdiOrderBoolDescendingVariant,
  mdiBellOutline,
  mdiAccountPlusOutline,
  mdiFaceAgent,
  mdiCogOutline,
  mdiLogout,
} from "@mdi/js";

export const data = {
  sidebarTop: [
    {
      iconLeft: true,
      showText: true,
      text: "Dashboard",
      css: "text-white text-xs md:text-sm",
      icon: mdiViewDashboardOutline,
      showBorders: false,
      href: "",
      showNotifications: false,
      notifications: 0,
      userInitials: "",
      showAvatar: false,
      iconSize: 1,
    },
    {
      iconLeft: true,
      showText: true,
      text: "Clients",
      css: "text-white text-xs md:text-sm",
      icon: mdiAccountMultiple,
      showBorders: false,
      href: "",
      showNotifications: false,
      notifications: 0,
      userInitials: "",
      showAvatar: false,
      iconSize: 1,
    },
    {
      iconLeft: true,
      showText: true,
      text: "AI Analysis",
      css: "text-white text-xs md:text-sm",
      icon: mdiOrderBoolDescendingVariant,
      showBorders: false,
      href: "",
      showNotifications: false,
      notifications: 0,
      userInitials: "",
      showAvatar: false,
      iconSize: 1,
    },
    {
      iconLeft: true,
      showText: true,
      text: "Insurance Portfolio",
      css: "text-white text-xs md:text-sm",
      icon: mdiViewDashboardOutline,
      showBorders: false,
      href: "",
      showNotifications: false,
      notifications: 0,
      userInitials: "",
      showAvatar: false,
      iconSize: 1,
    },
  ],
  sidebarBottom: [
    {
      iconLeft: true,
      showText: true,
      text: "Notifications",
      css: "text-white text-xs md:text-sm",
      icon: mdiBellOutline,
      showBorders: false,
      href: "",
      showNotifications: true,
      notifications: 5,
      userInitials: "",
      showAvatar: false,
      iconSize: 1,
    },
    {
      iconLeft: true,
      showText: true,
      text: "Invite a Friend",
      css: "text-white text-xs md:text-sm",
      icon: mdiAccountPlusOutline,
      showBorders: false,
      href: "",
      showNotifications: false,
      notifications: 0,
      userInitials: "",
      showAvatar: false,
      iconSize: 1,
    },
    {
      iconLeft: true,
      showText: true,
      text: "Support",
      css: "text-white text-xs md:text-sm",
      icon: mdiFaceAgent,
      showBorders: false,
      href: "",
      showNotifications: false,
      notifications: 0,
      userInitials: "",
      showAvatar: false,
      iconSize: 1,
    },
    {
      iconLeft: true,
      showText: true,
      text: "Settings",
      css: "text-white text-xs md:text-sm",
      icon: mdiCogOutline,
      showBorders: false,
      href: "",
      showNotifications: false,
      notifications: 0,
      userInitials: "",
      showAvatar: false,
      iconSize: 1,
    },
    {
      iconLeft: true,
      showText: true,
      text: "David Lovejoy",
      css: "text-white text-xs md:text-sm",
      icon: mdiCogOutline,
      showBorders: false,
      href: "",
      showNotifications: false,
      notifications: 0,
      userInitials: "DL",
      showAvatar: true,
      iconSize: 1,
    },
    {
      iconLeft: true,
      showText: true,
      text: "Log Out",
      css: "text-white text-xs md:text-sm",
      icon: mdiLogout,
      showBorders: false,
      href: "",
      showNotifications: false,
      notifications: 0,
      userInitials: "",
      showAvatar: false,
      iconSize: 1,
    },
  ],
  headers: [
    {
      title: "Basic Info",
      href: "basic-info",
      selected: false,
      inProgress: false,
      complete: false,
      error: false,
    },
    {
      title: "Family Information",
      href: "family-information",
      selected: true,
      inProgress: false,
      complete: true,
      error: false,
    },
    {
      title: "View Data",
      href: "view-data",
      selected: false,
      inProgress: false,
      complete: false,
      error: false,
    },
  ],

  preferences: [
    { value: "Investment Opportunities", label: "Investment Opportunities" },
    { value: "Low-Cost Premiums", label: "Low-Cost Premiums" },
    { value: "Medium Budget", label: "Medium Budget" },
  ],
};
